var config = [
 
    /******************************************         level 1 ----------- astronomy       ******************************************/
    {level:"1", theme: "astronomy", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"1", theme: "astronomy", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"1", theme: "astronomy", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"1", theme: "astronomy", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"1", theme: "astronomy", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"1", theme: "astronomy", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"1", theme: "astronomy", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    /******************************************         level 2 ----------- astronomy       ******************************************/
    {level:"2", theme: "astronomy", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"2", theme: "astronomy", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"2", theme: "astronomy", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"2", theme: "astronomy", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"2", theme: "astronomy", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"2", theme: "astronomy", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"2", theme: "astronomy", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    /******************************************         level 3 ----------- astronomy       ******************************************/
    {level:"3", theme: "astronomy", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"3", theme: "astronomy", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"3", theme: "astronomy", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"3", theme: "astronomy", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"3", theme: "astronomy", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"3", theme: "astronomy", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"3", theme: "astronomy", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    /******************************************         level 4 ----------- astronomy       ******************************************/
    {level:"4", theme: "astronomy", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"4", theme: "astronomy", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"4", theme: "astronomy", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"4", theme: "astronomy", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"4", theme: "astronomy", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"4", theme: "astronomy", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"4", theme: "astronomy", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    /******************************************         level 5 ----------- astronomy       ******************************************/
    {level:"5", theme: "astronomy", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"5", theme: "astronomy", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"5", theme: "astronomy", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"5", theme: "astronomy", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"5", theme: "astronomy", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"5", theme: "astronomy", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"5", theme: "astronomy", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    
    /******************************************         level 1 ----------- sport       ******************************************/
    {level:"1", theme: "sport", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"1", theme: "sport", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"1", theme: "sport", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"1", theme: "sport", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"1", theme: "sport", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"1", theme: "sport", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"1", theme: "sport", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    /******************************************         level 2 ----------- sport       ******************************************/
    {level:"2", theme: "sport", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"2", theme: "sport", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"2", theme: "sport", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"2", theme: "sport", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"2", theme: "sport", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"2", theme: "sport", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"2", theme: "sport", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    /******************************************         level 3 ----------- sport       ******************************************/
    {level:"3", theme: "sport", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"3", theme: "sport", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"3", theme: "sport", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"3", theme: "sport", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"3", theme: "sport", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"3", theme: "sport", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"3", theme: "sport", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    /******************************************         level 4 ----------- sport       ******************************************/
    {level:"4", theme: "sport", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"4", theme: "sport", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"4", theme: "sport", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"4", theme: "sport", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"4", theme: "sport", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"4", theme: "sport", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"4", theme: "sport", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    /******************************************         level 5 ----------- sport       ******************************************/
    {level:"5", theme: "sport", question: "how many planets are in the solar system?", answers: ["6", "7", "8", "9"], correct: 3},
    {level:"5", theme: "sport", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"5", theme: "sport", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"5", theme: "sport", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"5", theme: "sport", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"5", theme: "sport", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"5", theme: "sport", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    
  
    {level:"1", theme: "history", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"1", theme: "history", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"1", theme: "history", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"1", theme: "history", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"1", theme: "history", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"1", theme: "history", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"1", theme: "history", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},

    {level:"2", theme: "history", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"2", theme: "history", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"2", theme: "history", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"2", theme: "history", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"2", theme: "history", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"2", theme: "history", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"2", theme: "history", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
 
    {level:"3", theme: "history", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"3", theme: "history", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"3", theme: "history", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"3", theme: "history", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"3", theme: "history", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"3", theme: "history", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"3", theme: "history", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},

    {level:"4", theme: "history", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"4", theme: "history", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"4", theme: "history", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"4", theme: "history", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"4", theme: "history", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"4", theme: "history", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"4", theme: "history", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},

    {level:"5", theme: "history", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"5", theme: "history", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"5", theme: "history", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"5", theme: "history", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"5", theme: "history", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"5", theme: "history", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"5", theme: "history", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    
  
    {level:"1", theme: "classic music", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"1", theme: "classic music", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"1", theme: "classic music", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"1", theme: "classic music", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"1", theme: "classic music", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"1", theme: "classic music", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"1", theme: "classic music", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
   
    {level:"2", theme: "classic music", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"2", theme: "classic music", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"2", theme: "classic music", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"2", theme: "classic music", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"2", theme: "classic music", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"2", theme: "classic music", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"2", theme: "classic music", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
   
    {level:"3", theme: "classic music", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"3", theme: "classic music", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"3", theme: "classic music", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"3", theme: "classic music", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"3", theme: "classic music", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"3", theme: "classic music", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"3", theme: "classic music", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    
    {level:"4", theme: "classic music", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"4", theme: "classic music", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"4", theme: "classic music", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"4", theme: "classic music", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"4", theme: "classic music", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"4", theme: "classic music", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"4", theme: "classic music", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
  
    {level:"5", theme: "classic music", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"5", theme: "classic music", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"5", theme: "classic music", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"5", theme: "classic music", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"5", theme: "classic music", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"5", theme: "classic music", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"5", theme: "classic music", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    
    
    {level:"1", theme: "cinema", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"1", theme: "cinema", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"1", theme: "cinema", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"1", theme: "cinema", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"1", theme: "cinema", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"1", theme: "cinema", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"1", theme: "cinema", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},

    {level:"2", theme: "cinema", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"2", theme: "cinema", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"2", theme: "cinema", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"2", theme: "cinema", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"2", theme: "cinema", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"2", theme: "cinema", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"2", theme: "cinema", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},

    {level:"3", theme: "cinema", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"3", theme: "cinema", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"3", theme: "cinema", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"3", theme: "cinema", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"3", theme: "cinema", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"3", theme: "cinema", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"3", theme: "cinema", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},

    {level:"4", theme: "cinema", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"4", theme: "cinema", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"4", theme: "cinema", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"4", theme: "cinema", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"4", theme: "cinema", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"4", theme: "cinema", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"4", theme: "cinema", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},

    {level:"5", theme: "cinema", question: "how many planets are in the solar system?", answers : ["6", "7", "8", "9"], correct: 3},
    {level:"5", theme: "cinema", question: "how many times did Al Pacino took an academy aword?", answers : ["1", "2", "3", "4"], correct: 1},
    {level:"5", theme: "cinema", question: "Mozart died at the age of?", answers : ["26", "27", "28", "29"], correct: 2},
    {level:"5", theme: "cinema", question: "how many champions league did AC Milan won ?", answers: ["7", "8", "9", "10"], correct: 3},
    {level:"5", theme: "cinema", question: "At what year Carthage was built ?", answers: ["-814", "-230", "514", "814"], correct: 3},
    {level:"5", theme: "cinema", question: "which is the biggest planet in our solar system?", answers: ["jupiter", "Mars", "la terre", "neptune"], correct: 2},
    {level:"5", theme: "cinema", question: "The movie Fight club was directed by ", answers: ["David finsher", "Martin scorsese", "cristopher nolan", "robert de nero"], correct: 1},
    {level:"1", theme: "cinema", question: "Le directeur du God fadher est ", answers: ["Fransis copolla ", "Martin scorsese ", "Cristopher Nolan ", "Hatem bel Haj "], correct: "1"},
    {level: "1", theme: "cinema", question: "La Prémiere Oscar de Leonardo de caprio est à ", answers: ["2018", "2016", "2014", "2002"], correct: "2"},
    {level: "1", theme: "cinema", question: "quelle est l'origine de Robert de nero ", answers: ["Italien ", "Français ", "Anglais", "Japonais"], correct: "1"},
    {level: "1", theme: "cinema", question: "quelle est l'age de Brad Pitt", answers: ["56", "42", "58", "36"], correct: "3"},
    {level: "1", theme: "cinema", question: "The Intouchable est réalisé en ", answers: ["2011", "2012", "2013", "2014"], correct: "1"},
    {level: "1", theme: "cinema", question: "qui est l'acteur qui a gagné 3 oscars ", answers: ["Jack Nickelson ", "Ed harris", "Al pacino", "Daniel day Luis "], correct: "4"},
    {level:"2", theme: "cinema", question: "Le directeur du God fadher est ", answers: ["Fransis copolla ", "Martin scorsese ", "Cristopher Nolan ", "Hatem bel Haj "], correct: "1"},
    {level: "2", theme: "cinema", question: "La Prémiere Oscar de Leonardo de caprio est à ", answers: ["2018", "2016", "2014", "2002"], correct: "2"},
    {level: "2", theme: "cinema", question: "quelle est l'origine de Robert de nero ", answers: ["Italien ", "Français ", "Anglais", "Japonais"], correct: "1"},
    {level: "2", theme: "cinema", question: "quelle est l'age de Brad Pitt", answers: ["56", "42", "58", "36"], correct: "3"},
    {level: "2", theme: "cinema", question: "The Intouchable est réalisé en ", answers: ["2011", "2012", "2013", "2014"], correct: "1"},
    {level: "2", theme: "cinema", question: "qui est l'acteur qui a gagné 3 oscars ", answers: ["Jack Nickelson ", "Ed harris", "Al pacino", "Daniel day Luis "], correct: "4"},
    {level:"3", theme: "cinema", question: "Le directeur du God fadher est ", answers: ["Fransis copolla ", "Martin scorsese ", "Cristopher Nolan ", "Hatem bel Haj "], correct: "1"},
    {level: "3", theme: "cinema", question: "La Prémiere Oscar de Leonardo de caprio est à ", answers: ["2018", "2016", "2014", "2002"], correct: "2"},
    {level: "3", theme: "cinema", question: "quelle est l'origine de Robert de nero ", answers: ["Italien ", "Français ", "Anglais", "Japonais"], correct: "1"},
    {level: "3", theme: "cinema", question: "quelle est l'age de Brad Pitt", answers: ["56", "42", "58", "36"], correct: "3"},
    {level: "3", theme: "cinema", question: "The Intouchable est réalisé en ", answers: ["2011", "2012", "2013", "2014"], correct: "1"},
    {level: "3", theme: "cinema", question: "qui est l'acteur qui a gagné 3 oscars ", answers: ["Jack Nickelson ", "Ed harris", "Al pacino", "Daniel day Luis "], correct: "4"},
    {level:"4", theme: "cinema", question: "Le directeur du God fadher est ", answers: ["Fransis copolla ", "Martin scorsese ", "Cristopher Nolan ", "Hatem bel Haj "], correct: "1"},
    {level: "4", theme: "cinema", question: "La Prémiere Oscar de Leonardo de caprio est à ", answers: ["2018", "2016", "2014", "2002"], correct: "2"},
    {level: "4", theme: "cinema", question: "quelle est l'origine de Robert de nero ", answers: ["Italien ", "Français ", "Anglais", "Japonais"], correct: "1"},
    {level: "4", theme: "cinema", question: "quelle est l'age de Brad Pitt", answers: ["56", "42", "58", "36"], correct: "3"},
    {level: "4", theme: "cinema", question: "The Intouchable est réalisé en ", answers: ["2011", "2012", "2013", "2014"], correct: "1"},
    {level: "4", theme: "cinema", question: "qui est l'acteur qui a gagné 3 oscars ", answers: ["Jack Nickelson ", "Ed harris", "Al pacino", "Daniel day Luis "], correct: "4"},
    {level:"5", theme: "cinema", question: "Le directeur du God fadher est ", answers: ["Fransis copolla ", "Martin scorsese ", "Cristopher Nolan ", "Hatem bel Haj "], correct: "1"},
    {level: "5", theme: "cinema", question: "La Prémiere Oscar de Leonardo de caprio est à ", answers: ["2018", "2016", "2014", "2002"], correct: "2"},
    {level: "5", theme: "cinema", question: "quelle est l'origine de Robert de nero ", answers: ["Italien ", "Français ", "Anglais", "Japonais"], correct: "1"},
    {level: "5", theme: "cinema", question: "quelle est l'age de Brad Pitt", answers: ["56", "42", "58", "36"], correct: "3"},
    {level: "5", theme: "cinema", question: "The Intouchable est réalisé en ", answers: ["2011", "2012", "2013", "2014"], correct: "1"},
    {level: "5", theme: "cinema", question: "qui est l'acteur qui a gagné 3 oscars ", answers: ["Jack Nickelson ", "Ed harris", "Al pacino", "Daniel day Luis "], correct: "4"},
    
];
